/**
 * knowledgeInsights.js — Knowledge Gap Detection + Topic Recommendation + Draft Pipeline
 *
 * Mounting point: /api/internal/knowledge
 * Proteksi:       X-Internal-Key header (server-to-server) atau Bearer token (admin UI)
 *
 * Endpoints:
 *   GET   /gaps             — detectKnowledgeGaps()
 *   GET   /recommendations  — getRecommendedTopics()
 *   POST  /draft            — generateDraft(topic)
 *   POST  /auto-draft       — autoGenerateDrafts() → gap→draft→simpan ke kb_drafts
 *   GET   /drafts           — getDrafts(status)
 *   PATCH /drafts/:id       — updateDraftStatus(id, status)
 *
 * ADDITIVE-ONLY: tidak mengubah /api/chat, tidak mengubah retrieval.
 * kb_drafts tidak terhubung ke knowledge_base — tidak masuk ke retrieval.
 */
import { Router } from "express";
import {
  detectKnowledgeGaps,
  getRecommendedTopics,
  generateDraft,
  autoGenerateDrafts,
} from "../services/knowledgeGapService.js";
import {
  getDrafts,
  updateDraftStatus,
} from "../services/draftStorageService.js";

/**
 * @param {{ getAdminClient: Function, verifyAuth: Function, openRouterApiKey: string }} deps
 * @returns {Router}
 */
export function createKnowledgeInsightsRouter({ getAdminClient, verifyAuth, openRouterApiKey }) {
  const router  = Router();
  const svcDeps = { getAdminClient, openRouterApiKey };

  // ── Auth guard ─────────────────────────────────────────────────────────
  // Prioritas 1: X-Internal-Key header (server-to-server / automation)
  // Prioritas 2: Bearer token (admin UI di browser)
  async function guardInternal(req, res) {
    const envKey   = process.env.INTERNAL_API_KEY;
    const provided = req.headers["x-internal-key"];

    if (provided) {
      if (envKey && provided === envKey) return true;
      res.status(403).json({ error: "X-Internal-Key tidak valid" });
      return false;
    }

    try {
      const user = await verifyAuth(req.headers.authorization);
      if (!user) { res.status(401).json({ error: "Login diperlukan" }); return false; }
      return true;
    } catch {
      res.status(401).json({ error: "Autentikasi gagal" });
      return false;
    }
  }

  // ── Async wrapper ──────────────────────────────────────────────────────
  const h = (fn) => async (req, res) => {
    try { await fn(req, res); }
    catch (e) {
      console.error("[KnowledgeInsights]", e.message);
      res.status(500).json({ error: e.message || "Internal error" });
    }
  };

  // ── GET /gaps ──────────────────────────────────────────────────────────
  // Temukan query yang sering ditanya tapi KB-nya lemah/tidak ada/dapat rating buruk.
  // ?min_frequency=3 ?days=30
  router.get("/gaps", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;
    const minFrequency = Math.max(1, parseInt(req.query.min_frequency) || 3);
    const days         = Math.min(90, Math.max(1, parseInt(req.query.days) || 30));
    const gaps = await detectKnowledgeGaps(svcDeps, { minFrequency, days });
    res.json({ count: gaps.length, gaps });
  }));

  // ── GET /recommendations ───────────────────────────────────────────────
  // Grup gaps jadi topik terstruktur dengan prioritas high/medium/low.
  // ?min_frequency=3 ?days=30
  router.get("/recommendations", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;
    const minFrequency = Math.max(1, parseInt(req.query.min_frequency) || 3);
    const days         = Math.min(90, Math.max(1, parseInt(req.query.days) || 30));
    const topics = await getRecommendedTopics(svcDeps, { minFrequency, days });
    res.json({ count: topics.length, topics });
  }));

  // ── POST /draft ────────────────────────────────────────────────────────
  // Generate satu artikel panduan via OpenRouter. TIDAK disimpan otomatis.
  // Body: { topic: string, related_queries?: string[] }
  router.post("/draft", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;
    const { topic, related_queries } = req.body || {};
    if (!topic?.trim()) return res.status(400).json({ error: "Field 'topic' wajib diisi" });
    const draft = await generateDraft(topic.trim(), svcDeps, {
      relatedQueries: Array.isArray(related_queries) ? related_queries : [],
    });
    res.json(draft);
  }));

  // ── POST /auto-draft ───────────────────────────────────────────────────
  // Pipeline otomatis: ambil top-high-priority gaps → generate → simpan ke kb_drafts.
  // Anti-spam: max 3 topik per run, hanya priority='high'.
  // Body: { max_topics?: number (1-3), min_frequency?: number, days?: number }
  // Response: { generated, skipped, topics, errors }
  router.post("/auto-draft", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;

    const { max_topics, min_frequency, days } = req.body || {};
    const maxTopics    = Math.min(3, Math.max(1, parseInt(max_topics)    || 3));
    const minFrequency = Math.max(1, parseInt(min_frequency) || 3);
    const daysN        = Math.min(90, Math.max(1, parseInt(days) || 30));

    const result = await autoGenerateDrafts(svcDeps, { maxTopics, minFrequency, days: daysN });
    res.json(result);
  }));

  // ── GET /drafts ────────────────────────────────────────────────────────
  // Ambil list draft dari kb_drafts.
  // ?status=draft|approved|rejected|all  (default: draft)
  // ?limit=50  (max 100)
  // Response: { count, drafts: [...] }
  router.get("/drafts", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;

    const status = req.query.status || "draft";
    const limit  = Math.min(100, Math.max(1, parseInt(req.query.limit) || 50));

    const drafts = await getDrafts(status, svcDeps, { limit });
    res.json({ count: drafts.length, drafts });
  }));

  // ── PATCH /drafts/:id ─────────────────────────────────────────────────
  // Update status draft: approved | rejected | draft
  // Body: { status: "approved" | "rejected" | "draft" }
  // Response: updated draft row
  router.patch("/drafts/:id", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;

    const { id }     = req.params;
    const { status } = req.body || {};
    if (!status) return res.status(400).json({ error: "Field 'status' wajib diisi" });

    const updated = await updateDraftStatus(id, status, svcDeps);
    res.json(updated);
  }));

  return router;
}
