/**
 * knowledgeInsights.js — Knowledge Gap Detection + Topic Recommendation + Draft Pipeline
 *
 * Mounting point: /api/internal/knowledge
 * Proteksi:       X-Internal-Key header (server-to-server) atau Bearer token (admin UI)
 *
 * Endpoints:
 *   GET   /gaps             — detectKnowledgeGaps()
 *   GET   /recommendations  — getRecommendedTopics()
 *   POST  /draft            — generateDraft(topic)
 *   POST  /auto-draft       — autoGenerateDrafts() → gap→draft→simpan ke kb_drafts
 *   GET   /drafts           — getDrafts(status)
 *   PATCH /drafts/:id       — updateDraftStatus(id, status) — ubah status SAJA
 *   POST  /drafts/:id/publish — salin draft ke knowledge_base + embed (admin only)
 *
 * Rantai lengkapnya:
 *   pertanyaan tak terjawab → missing_topics → detectKnowledgeGaps()
 *     → generateDraft() → kb_drafts → review admin → /publish
 *     → knowledge_base + embedding → ikut retrieval
 *
 * Dulu rantai ini buntu di kb_drafts: publishDraftToKnowledgeBase() masih
 * placeholder yang sengaja throw, jadi draft bisa di-approve tapi tidak pernah
 * sampai ke knowledge_base — AI tidak pernah benar-benar bertambah pintar dari
 * proses ini. Sekarang sudah tersambung.
 *
 * Yang TETAP manual dan memang sengaja: memilih `category` saat publish.
 * knowledge_base.category NOT NULL, dan menebak kategori otomatis persis jenis
 * kesalahan yang merusak kualitas retrieval — admin yang memutuskan.
 */
import { Router } from "express";
import {
  detectKnowledgeGaps,
  getRecommendedTopics,
  generateDraft,
  autoGenerateDrafts,
} from "../services/knowledgeGapService.js";
import {
  getDrafts,
  updateDraftStatus,
  publishDraftToKnowledgeBase,
} from "../services/draftStorageService.js";

/**
 * @param {{ getAdminClient: Function, verifyAuth: Function, verifyAdminUser?: Function, embedArticle?: Function, openRouterApiKey: string }} deps
 * @returns {Router}
 */
export function createKnowledgeInsightsRouter({ getAdminClient, verifyAuth, verifyAdminUser, embedArticle, openRouterApiKey }) {
  const router  = Router();
  const svcDeps = { getAdminClient, openRouterApiKey, embedArticle };

  // ── Auth guard ─────────────────────────────────────────────────────────
  // Prioritas 1: X-Internal-Key header (server-to-server / automation)
  // Prioritas 2: Bearer token (admin UI di browser)
  async function guardInternal(req, res) {
    const envKey   = process.env.INTERNAL_API_KEY;
    const provided = req.headers["x-internal-key"];

    if (provided) {
      if (envKey && provided === envKey) return true;
      res.status(403).json({ error: "X-Internal-Key tidak valid" });
      return false;
    }

    try {
      const user = await verifyAuth(req.headers.authorization);
      if (!user) { res.status(401).json({ error: "Login diperlukan" }); return false; }
      return true;
    } catch {
      res.status(401).json({ error: "Autentikasi gagal" });
      return false;
    }
  }

  // ── Async wrapper ──────────────────────────────────────────────────────
  const h = (fn) => async (req, res) => {
    try { await fn(req, res); }
    catch (e) {
      console.error("[KnowledgeInsights]", e.message);
      res.status(500).json({ error: e.message || "Internal error" });
    }
  };

  // ── GET /gaps ──────────────────────────────────────────────────────────
  // Temukan query yang sering ditanya tapi KB-nya lemah/tidak ada/dapat rating buruk.
  // ?min_frequency=3 ?days=30
  router.get("/gaps", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;
    const minFrequency = Math.max(1, parseInt(req.query.min_frequency) || 3);
    const days         = Math.min(90, Math.max(1, parseInt(req.query.days) || 30));
    const gaps = await detectKnowledgeGaps(svcDeps, { minFrequency, days });
    res.json({ count: gaps.length, gaps });
  }));

  // ── GET /recommendations ───────────────────────────────────────────────
  // Grup gaps jadi topik terstruktur dengan prioritas high/medium/low.
  // ?min_frequency=3 ?days=30
  router.get("/recommendations", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;
    const minFrequency = Math.max(1, parseInt(req.query.min_frequency) || 3);
    const days         = Math.min(90, Math.max(1, parseInt(req.query.days) || 30));
    const topics = await getRecommendedTopics(svcDeps, { minFrequency, days });
    res.json({ count: topics.length, topics });
  }));

  // ── POST /draft ────────────────────────────────────────────────────────
  // Generate satu artikel panduan via OpenRouter. TIDAK disimpan otomatis.
  // Body: { topic: string, related_queries?: string[] }
  router.post("/draft", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;
    const { topic, related_queries } = req.body || {};
    if (!topic?.trim()) return res.status(400).json({ error: "Field 'topic' wajib diisi" });
    const draft = await generateDraft(topic.trim(), svcDeps, {
      relatedQueries: Array.isArray(related_queries) ? related_queries : [],
    });
    res.json(draft);
  }));

  // ── POST /auto-draft ───────────────────────────────────────────────────
  // Pipeline otomatis: ambil top-high-priority gaps → generate → simpan ke kb_drafts.
  // Anti-spam: max 3 topik per run, hanya priority='high'.
  // Body: { max_topics?: number (1-3), min_frequency?: number, days?: number }
  // Response: { generated, skipped, topics, errors }
  router.post("/auto-draft", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;

    const { max_topics, min_frequency, days } = req.body || {};
    const maxTopics    = Math.min(3, Math.max(1, parseInt(max_topics)    || 3));
    const minFrequency = Math.max(1, parseInt(min_frequency) || 3);
    const daysN        = Math.min(90, Math.max(1, parseInt(days) || 30));

    const result = await autoGenerateDrafts(svcDeps, { maxTopics, minFrequency, days: daysN });
    res.json(result);
  }));

  // ── GET /drafts ────────────────────────────────────────────────────────
  // Ambil list draft dari kb_drafts.
  // ?status=draft|approved|rejected|all  (default: draft)
  // ?limit=50  (max 100)
  // Response: { count, drafts: [...] }
  router.get("/drafts", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;

    const status = req.query.status || "draft";
    const limit  = Math.min(100, Math.max(1, parseInt(req.query.limit) || 50));

    const drafts = await getDrafts(status, svcDeps, { limit });
    res.json({ count: drafts.length, drafts });
  }));

  // ── PATCH /drafts/:id ─────────────────────────────────────────────────
  // Update status draft: approved | rejected | draft
  // Body: { status: "approved" | "rejected" | "draft" }
  // Response: updated draft row + a `note` when status="approved" — this
  // ONLY flips the kb_drafts.status column, it does NOT copy the draft
  // into knowledge_base (publishDraftToKnowledgeBase() is unimplemented —
  // see file header). Without the note, "approved" reads as "published".
  router.patch("/drafts/:id", h(async (req, res) => {
    if (!(await guardInternal(req, res))) return;

    const { id }     = req.params;
    const { status } = req.body || {};
    if (!status) return res.status(400).json({ error: "Field 'status' wajib diisi" });

    const updated = await updateDraftStatus(id, status, svcDeps);
    const note = status === "approved"
      ? "Status diubah ke 'approved', TAPI ini hanya mengubah kolom status. Untuk benar-benar memasukkan draft ke knowledge_base dan ikut retrieval AI, pakai POST /drafts/:id/publish (butuh category)."
      : undefined;
    res.json(note ? { ...updated, note } : updated);
  }));

  // ── POST /drafts/:id/publish ──────────────────────────────────────────
  // Salin draft ke knowledge_base + embed, lalu tandai draft 'approved'.
  // Inilah langkah yang dulu hilang: tanpa ini, rantai
  // missing_topics → gap → draft → approve berhenti di kb_drafts dan AI tidak
  // pernah benar-benar bertambah pintar dari proses tersebut.
  //
  // Body: { category: string (wajib), article_type?: "narrative"|"step_by_step" }
  // Auth: WAJIB admin (bukan sekadar user login) — ini menulis ke knowledge_base
  // yang langsung dipakai menjawab semua user.
  router.post("/drafts/:id/publish", h(async (req, res) => {
    if (typeof verifyAdminUser !== "function") {
      return res.status(500).json({ error: "verifyAdminUser tidak tersedia di server ini" });
    }
    const admin = await verifyAdminUser(req.headers.authorization);
    if (!admin) return res.status(403).json({ error: "Hanya admin yang boleh publish draft ke knowledge_base" });

    const { category, article_type } = req.body || {};
    if (!category?.trim()) {
      return res.status(400).json({ error: "Field 'category' wajib diisi — pilih kategori knowledge_base untuk artikel ini" });
    }

    const result = await publishDraftToKnowledgeBase(req.params.id, svcDeps, {
      category: category.trim(),
      authorId: admin.id,
      articleType: article_type === "step_by_step" ? "step_by_step" : "narrative",
    });

    res.json({
      published: true,
      article_id: result.article.id,
      title: result.article.title,
      category: result.article.category,
      note: "Artikel sudah masuk knowledge_base dan sedang di-embed di background. Biasanya ikut retrieval dalam beberapa detik.",
    });
  }));

  return router;
}
