/**
 * api/engine/responseFormatter.js
 * Post-processing and structural validation for AINA responses.
 *
 * This module defines:
 *   1. Response structure schemas (what a good response looks like)
 *   2. Output validation (detect hallucination signals, bad patterns)
 *   3. Source attribution builder (source badge data for the frontend)
 *   4. Response sanitization helpers
 */

/* ── Response structure schemas ───────────────────────────────────────────── */

/**
 * Standard response structure for GENERAL (factual/conversational) queries.
 *
 * Sections (all optional except main_answer):
 *   1. short_answer   — 1-2 sentence direct answer to the question
 *   2. main_answer    — Full explanation, may include paragraphs or bullet lists
 *   3. important_note — ⚠️ caveat, warning, or critical information (if needed)
 *   4. source_section — auto-generated by frontend; NOT written by the model
 */
export const GENERAL_RESPONSE_SCHEMA = {
  sections: ["short_answer", "main_answer", "important_note"],
  rules: [
    "Start with the direct answer — no preamble.",
    "Keep important_note only if genuinely critical (not just a disclaimer).",
    "Source attribution is handled by the frontend — do not write 'Sumber:' in the text.",
    "If uncertain, say so clearly — do not sound fully confident about unverified info.",
  ],
};

/**
 * Standard response structure for HOW-TO / PROCEDURAL queries.
 *
 * Sections:
 *   1. short_answer    — 1 framing sentence about the process
 *   2. steps           — Numbered list (1. 2. 3.) — each step = one action
 *   3. important_note  — ⚠️ critical warnings or common mistakes (optional)
 *   4. practical_tip   — 💡 time-saving tip or shortcut (optional)
 *   5. source_section  — auto-generated by frontend
 */
export const PROCEDURAL_RESPONSE_SCHEMA = {
  sections: ["short_answer", "steps", "important_note", "practical_tip"],
  rules: [
    "Each step covers exactly ONE action — never bundle multiple actions in one step.",
    "Action first, detail second — within each step.",
    "Max 2 sentences per step.",
    "important_note uses ⚠️ prefix; practical_tip uses 💡 prefix.",
    "Skip optional sections if there's genuinely nothing to add.",
  ],
};

/* ── Bad pattern detector ─────────────────────────────────────────────────── */

/**
 * Patterns that indicate a low-quality or rule-violating response.
 * Used to flag responses for review or retry.
 *
 * @typedef {{ type: string, pattern: RegExp, severity: "warn" | "block" }} BadPattern
 * @type {BadPattern[]}
 */
const BAD_PATTERNS = [
  // Model claiming to search or check the web (it cannot — responses are final)
  {
    type: "waiting_language",
    pattern: /\b(tunggu sebentar|aku cek dulu|aku cari dulu|cek web dulu|sedang mencari|harap tunggu|biar aku cek)\b/i,
    severity: "block",
  },
  // Sycophantic openers (explicitly forbidden by system prompt)
  {
    type: "sycophantic_opener",
    pattern: /^(tentu!|baik!|siap!|dengan senang hati!|tentu saja!|pastinya!)/i,
    severity: "warn",
  },
  // Model exposing its own instructions or meta-commentary
  {
    type: "meta_exposure",
    pattern: /\b(instruksi saya|sistem prompt|sebagai AI|sebagai asisten AI|saya diprogram)\b/i,
    severity: "warn",
  },
  // Hallucinated exchange rate (any specific EGP/IDR number without data context)
  // Note: only flagged when no exchange context was provided — caller must check this
  {
    type: "hallucinated_rate",
    pattern: /\b1\s*EGP\s*=\s*[Rp\s]*[\d,]+\b/i,
    severity: "warn",
  },
  // Closing filler phrases (forbidden by system prompt for informational responses)
  {
    type: "filler_closing",
    pattern: /(semoga membantu|jangan ragu bertanya|feel free to ask|hope this helps|ada yang bisa aku bantu lagi|ada pertanyaan lain)\s*[!.]*\s*$/i,
    severity: "warn",
  },
  // Bare-list opener: response starts with "Berikut adalah..." immediately dumping a list
  {
    type: "bare_list_opener",
    pattern: /^Berikut (adalah |ini )?(beberapa |)[\w\s,()-]+(nya|:)\s*\n/i,
    severity: "warn",
  },
  // Encyclopedic opener: first sentence is a dry dictionary-style definition
  {
    type: "encyclopedic_opener",
    pattern: /^[A-Z][a-zéèàâêî\u00C0-\u017E]+(?:\s+[a-z]+)? adalah (sebuah|suatu|satu|jenis) /i,
    severity: "warn",
  },
];

/**
 * Validate a model response for common quality issues.
 * Returns a list of detected issues (empty = clean response).
 *
 * @param {string} responseText - Raw text from the AI model
 * @param {{ hasExchangeContext: boolean }} options
 * @returns {{ type: string, severity: string, match: string }[]}
 */
export function validateResponse(responseText, options = {}) {
  if (!responseText || typeof responseText !== "string") return [];

  const issues = [];
  for (const { type, pattern, severity } of BAD_PATTERNS) {
    // Skip hallucinated_rate check when exchange data was actually provided
    if (type === "hallucinated_rate" && options.hasExchangeContext) continue;

    const match = responseText.match(pattern);
    if (match) {
      issues.push({ type, severity, match: match[0] });
    }
  }
  return issues;
}

/* ── Source attribution builder ───────────────────────────────────────────── */

/**
 * Build structured source attribution data for the frontend badge system.
 * The frontend renders this as source chips below each AINA message.
 *
 * @param {object} sourceLog - The sourceLog object built in the /api/chat handler
 * @returns {object[]} Array of source badge objects
 *
 * Badge shape: { label: string, tier: "high"|"medium"|"low", url?: string }
 */
export function buildSourceBadges(sourceLog) {
  const badges = [];

  if (!sourceLog) return badges;

  if (sourceLog.kb_used) {
    badges.push({
      label: "Knowledge Base AINA",
      tier: "high",
      description: "Informasi dari kontributor AINA, telah diverifikasi",
    });
  }

  if (sourceLog.external_type === "perplexity" && sourceLog.external_success) {
    badges.push({
      label: "Pencarian Web",
      tier: "high",
      description: "Hasil pencarian web real-time via Perplexity",
    });
  }

  if (sourceLog.external_type === "wiki_ddg" && sourceLog.external_success) {
    if (sourceLog.fallback_used) {
      badges.push({
        label: "Wikipedia",
        tier: "medium",
        description: "Ensiklopedia publik — umumnya akurat, bisa tidak terkini",
      });
    }
  }

  if (sourceLog.external_type === "currency_api" && sourceLog.external_success) {
    badges.push({
      label: "Kurs Real-time",
      tier: "high",
      description: "Data kurs langsung dari exchange rate API",
    });
  }

  if (badges.length === 0 && sourceLog.final_source === "model_fallback") {
    badges.push({
      label: "Pengetahuan Model",
      tier: "low",
      description: "Berdasarkan pengetahuan training model AI — perlu verifikasi untuk info terkini",
    });
  }

  return badges;
}

/* ── Response post-processor ──────────────────────────────────────────────── */

/**
 * Apply lightweight post-processing to a model response.
 * Removes prohibited patterns and auto-corrects known BAD_PATTERN violations.
 *
 * Transformations applied (in order):
 *   1. Strip sycophantic openers ("Tentu!", "Baik!", "Siap!", etc.)
 *   2. Remove sentences containing waiting_language ("tunggu sebentar", "aku cek dulu", etc.)
 *   3. Strip trailing filler phrases ("Semoga membantu!", etc.)
 *
 * This is a post-generation correction layer — a zero-cost "retry" for recoverable issues.
 *
 * @param {string} text - Raw model response
 * @returns {string} Cleaned response text
 */
export function postProcessResponse(text) {
  if (!text || typeof text !== "string") return text;

  let cleaned = text;

  // 1. Strip sycophantic openers at the very start
  cleaned = cleaned.replace(
    /^(tentu!|baik!|siap!|dengan senang hati!|tentu saja!|pastinya!|oke!|ok!|sure!|tentu,|baik,|siap,)\s*/i,
    ""
  );

  // 2. Strip hollow "Berikut adalah/ini..." as the SOLE opening line (with nothing before it).
  //    These openers dump a list immediately without any framing — feels robotic.
  //    Pattern: response starts with "Berikut adalah/ini X:" or "Berikut X-nya:" and is immediately
  //    followed by a blank line + list. We remove that opener so the list speaks for itself,
  //    which is cleaner than a bare "Berikut adalah 5 hal:" with no context sentence.
  cleaned = cleaned.replace(
    /^(Berikut (adalah |ini )?(beberapa |)[\w\s,()-]+(nya|:)\s*\n)/i,
    ""
  );

  // 3. Strip bare structural openers that add no informational value
  cleaned = cleaned.replace(
    /^(Penjelasannya (adalah |)sebagai berikut\s*:\s*\n)/i,
    ""
  );

  // 4. Remove sentences that contain waiting_language (model hallucinating a search state)
  const WAITING_PHRASES = [
    /tunggu sebentar/i,
    /aku cek dulu/i,
    /aku cari dulu/i,
    /cek web dulu/i,
    /sedang mencari/i,
    /harap tunggu/i,
    /biar aku cek/i,
  ];
  for (const pattern of WAITING_PHRASES) {
    if (pattern.test(cleaned)) {
      cleaned = cleaned
        .split(/(?<=[.!?])\s+/)
        .filter(sentence => !pattern.test(sentence))
        .join(" ");
      console.warn(`[PostProcess] stripped waiting_language sentence: ${pattern}`);
    }
  }

  // 5. Strip trailing filler closings (broad patterns)
  cleaned = cleaned.replace(
    /\n*(semoga (surat|jawaban|penjelasan|contoh|info|tulisan|ini|artikel|terjemahan)?[\w\s]*(membantu|bermanfaat)[\w\s]*[!.]*|semoga (membantu|bermanfaat|bisa membantu)[!.]*|jangan ragu (untuk |)bertanya[!.]*|feel free to ask[!.]*|hope this helps[!.]*|ada (yang |hal )?(bisa|lain) (aku|saya) bantu\??|ada pertanyaan lain\??)\s*$/gi,
    ""
  ).trim();

  // 6. Strip repeated blank lines (3+ → 2)
  cleaned = cleaned.replace(/\n{3,}/g, "\n\n");

  return cleaned;
}

/* ── Query type classifier (for schema selection) ─────────────────────────── */

/**
 * Select the appropriate response schema based on intent.
 *
 * @param {string} intentPrimary - From detectIntent().primary
 * @returns {object} GENERAL_RESPONSE_SCHEMA or PROCEDURAL_RESPONSE_SCHEMA
 */
export function selectResponseSchema(intentPrimary) {
  const proceduralIntents = new Set(["procedural", "confused_procedural"]);
  return proceduralIntents.has(intentPrimary)
    ? PROCEDURAL_RESPONSE_SCHEMA
    : GENERAL_RESPONSE_SCHEMA;
}

/* ── AINA Response Formatter ──────────────────────────────────────────────── */

/**
 * Split overly long prose paragraphs into shorter, readable ones.
 * Conservative: only splits plain-text blocks over 80 words.
 * Preserves code blocks, Markdown tables, headings, and lists.
 *
 * @param {string} text
 * @returns {string}
 */
function splitLongParagraphs(text) {
  const WORD_THRESHOLD = 80;
  const TARGET_CHUNK_WORDS = 55;

  const blocks = text.split(/\n\n+/);
  const processed = blocks.map(block => {
    const trimmed = block.trim();

    // Skip: code fences, tables, headings, list items, blockquotes
    if (
      trimmed.startsWith("```")   ||
      trimmed.startsWith("|")     ||
      trimmed.startsWith("#")     ||
      trimmed.startsWith(">")     ||
      /^\s*[-*\d]/.test(trimmed)  ||
      trimmed.includes("\n|")     ||
      trimmed.includes("\n```")
    ) return block;

    const wordCount = trimmed.split(/\s+/).length;
    if (wordCount <= WORD_THRESHOLD) return block;

    // Split at sentence ends, aiming for TARGET_CHUNK_WORDS per chunk
    const sentenceRe = /[^.!?]*[.!?]+(?:\s|$)/g;
    const sentences = trimmed.match(sentenceRe) ?? [trimmed];
    const chunks = [];
    let current = "";
    let currentWords = 0;

    for (const sentence of sentences) {
      const sw = sentence.trim().split(/\s+/).length;
      if (currentWords + sw > TARGET_CHUNK_WORDS && current.trim()) {
        chunks.push(current.trim());
        current = sentence;
        currentWords = sw;
      } else {
        current += sentence;
        currentWords += sw;
      }
    }
    if (current.trim()) chunks.push(current.trim());

    return chunks.join("\n\n");
  });

  return processed.join("\n\n");
}

/**
 * Convert prose sequential patterns ("Pertama... Kedua... Ketiga...") into
 * proper Markdown numbered lists. Only activates when at least two ordinals
 * are detected in the same paragraph block.
 *
 * @param {string} text
 * @returns {string}
 */
function normalizeSequentialList(text) {
  const ORDINALS = [
    [/(?<!\d)(?:^|\s)pertama[,:]?\s+/gim,   "\n1. "],
    [/(?<!\d)(?:^|\s)kedua[,:]?\s+/gim,     "\n2. "],
    [/(?<!\d)(?:^|\s)ketiga[,:]?\s+/gim,    "\n3. "],
    [/(?<!\d)(?:^|\s)keempat[,:]?\s+/gim,   "\n4. "],
    [/(?<!\d)(?:^|\s)kelima[,:]?\s+/gim,    "\n5. "],
    [/(?<!\d)(?:^|\s)keenam[,:]?\s+/gim,    "\n6. "],
    [/(?<!\d)(?:^|\s)ketujuh[,:]?\s+/gim,   "\n7. "],
  ];

  // Only trigger when at least "pertama" + "kedua" appear together
  if (!/\bpertama\b/i.test(text) || !/\bkedua\b/i.test(text)) return text;

  // Don't process if already inside a list block (numbered or bullet)
  if (/^\s*[1-9]\.\s/m.test(text) || /^\s*[-*]\s/m.test(text)) return text;

  let result = text;
  for (const [pattern, replacement] of ORDINALS) {
    result = result.replace(pattern, replacement);
  }
  // Clean up any leading newline created at the very start
  return result.replace(/^\n+/, "");
}

/**
 * Strip additional robotic openers that postProcessResponse may miss.
 * Runs AFTER postProcessResponse, so only catches residual patterns.
 *
 * @param {string} text
 * @returns {string}
 */
function stripResiduaLOpeners(text) {
  return text.replace(
    /^(pertanyaan (yang |)bagus[!.]?\s*|pertanyaan (yang |)menarik[!.]?\s*|wah,?\s*pertanyaan (yang |)(bagus|menarik)[!.]?\s*|izinkan (aku|saya) menjelaskan[.,!:]?\s*|untuk menjawab pertanyaan (kamu|anda)[,:]?\s*|tentu,?\s*(aku|saya) (akan |)(menjelaskan|menjawab)[.,!:]?\s*|dalam konteks ini[,:]?\s*|membahas topik ini[,:]?\s*|berikut (adalah |)penjelasan(nya)?[,:]?\s*|sebagai AI[^,\n]*,\s*)/i,
    ""
  );
}

/**
 * Ensure the trust-layer footer is present in substantive responses.
 * If the model followed the system prompt, it will already be there.
 * This is a safety net for cases where it was omitted.
 *
 * @param {string} text
 * @param {{ label: string, trust: string }} sourceMeta
 * @param {string} intentPrimary
 * @returns {string}
 */
function ensureTrustFooter(text, sourceMeta, intentPrimary) {
  if (!sourceMeta?.label || !sourceMeta?.trust) return text;

  const CASUAL_INTENTS = new Set(["casual", "brainstorming"]);
  const isCasual     = CASUAL_INTENTS.has(intentPrimary);
  const isTooShort   = text.trim().length < 140;
  const endsQuestion = /\?\s*$/.test(text.trim());
  const hasFooter    = /\*Sumber:.*·.*Kepercayaan:/i.test(text);

  // Skip footer for: casual chat, very short replies, tanya-balik questions, already present
  if (isCasual || isTooShort || endsQuestion || hasFooter) return text;

  return text.trimEnd() + `\n\n---\n*Sumber: ${sourceMeta.label} · Kepercayaan: ${sourceMeta.trust}*`;
}

/**
 * AINA post-processing formatter.
 * Runs after postProcessResponse on the complete response text, right before
 * the `done` event is sent to the frontend.
 *
 * Pipeline (in order):
 *   1. Strip residual robotic openers
 *   2. Normalize sequential prose lists → Markdown numbered list
 *   3. Split long prose paragraphs into readable chunks
 *   4. Normalize spacing (3+ blank lines → 2)
 *   5. Ensure trust-layer footer is present
 *   6. Safety fallback if output is too short after cleaning
 *
 * Guarantees:
 *   - Never runs on empty / non-string input
 *   - Never strips structural Markdown (tables, code blocks, lists, headings)
 *   - Never modifies Arabic text blocks
 *   - Returns original text if an internal error occurs
 *
 * @param {string} text       — Processed response from postProcessResponse
 * @param {object} context    — Pipeline context
 * @param {string}  context.intentPrimary  — Detected intent
 * @param {object}  context.sourceMeta     — { label, trust } for footer
 * @returns {string} Final formatted response
 */
export function formatAINAResponse(text, context = {}) {
  if (!text || typeof text !== "string") return text ?? "";

  const { intentPrimary = "factual", sourceMeta = null } = context;

  try {
    let result = text;

    // 1. Strip residual robotic openers (safety net after postProcessResponse)
    result = stripResiduaLOpeners(result);

    // 2. Normalize sequential prose lists
    result = normalizeSequentialList(result);

    // 3. Split overly long paragraphs (conservative, skips all structured Markdown)
    result = splitLongParagraphs(result);

    // 4. Normalize spacing
    result = result.replace(/\n{3,}/g, "\n\n").trim();

    // 5. Ensure trust footer
    result = ensureTrustFooter(result, sourceMeta, intentPrimary);

    // 6. Safety fallback — if everything was stripped, return minimal message
    if (result.trim().length < 20) {
      console.warn("[Formatter] safety fallback triggered — output too short after formatting");
      return text.trim().length > 20 ? text.trim() : "Maaf, aku tidak dapat menghasilkan jawaban yang baik. Coba ulangi pertanyaanmu.";
    }

    return result;
  } catch (err) {
    // Never crash the pipeline — return original text on any error
    console.error("[Formatter] unexpected error:", err.message);
    return text;
  }
}
