/**
 * api/engine/responseFormatter.js
 * Post-processing and structural validation for AINA responses.
 *
 * This module defines:
 *   1. Response structure schemas (what a good response looks like)
 *   2. Output validation (detect hallucination signals, bad patterns)
 *   3. Source attribution builder (source badge data for the frontend)
 *   4. Response sanitization helpers
 */

/* ── Response structure schemas ───────────────────────────────────────────── */

/**
 * Standard response structure for GENERAL (factual/conversational) queries.
 *
 * Sections (all optional except main_answer):
 *   1. short_answer   — 1-2 sentence direct answer to the question
 *   2. main_answer    — Full explanation, may include paragraphs or bullet lists
 *   3. important_note — ⚠️ caveat, warning, or critical information (if needed)
 *   4. source_section — auto-generated by frontend; NOT written by the model
 */
export const GENERAL_RESPONSE_SCHEMA = {
  sections: ["short_answer", "main_answer", "important_note"],
  rules: [
    "Start with the direct answer — no preamble.",
    "Keep important_note only if genuinely critical (not just a disclaimer).",
    "Source attribution is handled by the frontend — do not write 'Sumber:' in the text.",
    "If uncertain, say so clearly — do not sound fully confident about unverified info.",
  ],
};

/**
 * Standard response structure for HOW-TO / PROCEDURAL queries.
 *
 * Sections:
 *   1. short_answer    — 1 framing sentence about the process
 *   2. steps           — Numbered list (1. 2. 3.) — each step = one action
 *   3. important_note  — ⚠️ critical warnings or common mistakes (optional)
 *   4. practical_tip   — 💡 time-saving tip or shortcut (optional)
 *   5. source_section  — auto-generated by frontend
 */
export const PROCEDURAL_RESPONSE_SCHEMA = {
  sections: ["short_answer", "steps", "important_note", "practical_tip"],
  rules: [
    "Each step covers exactly ONE action — never bundle multiple actions in one step.",
    "Action first, detail second — within each step.",
    "Max 2 sentences per step.",
    "important_note uses ⚠️ prefix; practical_tip uses 💡 prefix.",
    "Skip optional sections if there's genuinely nothing to add.",
  ],
};

/* ── Bad pattern detector ─────────────────────────────────────────────────── */

/**
 * Patterns that indicate a low-quality or rule-violating response.
 * Used to flag responses for review or retry.
 *
 * @typedef {{ type: string, pattern: RegExp, severity: "warn" | "block" }} BadPattern
 * @type {BadPattern[]}
 */
const BAD_PATTERNS = [
  // Model claiming to search or check the web (it cannot — responses are final)
  {
    type: "waiting_language",
    pattern: /\b(tunggu sebentar|aku cek dulu|aku cari dulu|cek web dulu|sedang mencari|harap tunggu|biar aku cek)\b/i,
    severity: "block",
  },
  // Sycophantic openers (explicitly forbidden by system prompt)
  {
    type: "sycophantic_opener",
    pattern: /^(tentu!|baik!|siap!|dengan senang hati!|tentu saja!|pastinya!)/i,
    severity: "warn",
  },
  // Model exposing its own instructions or meta-commentary
  {
    type: "meta_exposure",
    pattern: /\b(instruksi saya|sistem prompt|sebagai AI|sebagai asisten AI|saya diprogram)\b/i,
    severity: "warn",
  },
  // Hallucinated exchange rate (any specific EGP/IDR number without data context)
  // Note: only flagged when no exchange context was provided — caller must check this
  {
    type: "hallucinated_rate",
    pattern: /\b1\s*EGP\s*=\s*[Rp\s]*[\d,]+\b/i,
    severity: "warn",
  },
  // Closing filler phrases (forbidden by system prompt for informational responses)
  {
    type: "filler_closing",
    pattern: /(semoga membantu|jangan ragu bertanya|feel free to ask|hope this helps)\s*[!.]*\s*$/i,
    severity: "warn",
  },
];

/**
 * Validate a model response for common quality issues.
 * Returns a list of detected issues (empty = clean response).
 *
 * @param {string} responseText - Raw text from the AI model
 * @param {{ hasExchangeContext: boolean }} options
 * @returns {{ type: string, severity: string, match: string }[]}
 */
export function validateResponse(responseText, options = {}) {
  if (!responseText || typeof responseText !== "string") return [];

  const issues = [];
  for (const { type, pattern, severity } of BAD_PATTERNS) {
    // Skip hallucinated_rate check when exchange data was actually provided
    if (type === "hallucinated_rate" && options.hasExchangeContext) continue;

    const match = responseText.match(pattern);
    if (match) {
      issues.push({ type, severity, match: match[0] });
    }
  }
  return issues;
}

/* ── Source attribution builder ───────────────────────────────────────────── */

/**
 * Build structured source attribution data for the frontend badge system.
 * The frontend renders this as source chips below each AINA message.
 *
 * @param {object} sourceLog - The sourceLog object built in the /api/chat handler
 * @returns {object[]} Array of source badge objects
 *
 * Badge shape: { label: string, tier: "high"|"medium"|"low", url?: string }
 */
export function buildSourceBadges(sourceLog) {
  const badges = [];

  if (!sourceLog) return badges;

  if (sourceLog.kb_used) {
    badges.push({
      label: "Knowledge Base AINA",
      tier: "high",
      description: "Informasi dari kontributor AINA, telah diverifikasi",
    });
  }

  if (sourceLog.external_type === "perplexity" && sourceLog.external_success) {
    badges.push({
      label: "Pencarian Web",
      tier: "high",
      description: "Hasil pencarian web real-time via Perplexity",
    });
  }

  if (sourceLog.external_type === "wiki_ddg" && sourceLog.external_success) {
    if (sourceLog.fallback_used) {
      badges.push({
        label: "Wikipedia",
        tier: "medium",
        description: "Ensiklopedia publik — umumnya akurat, bisa tidak terkini",
      });
    }
  }

  if (sourceLog.external_type === "currency_api" && sourceLog.external_success) {
    badges.push({
      label: "Kurs Real-time",
      tier: "high",
      description: "Data kurs langsung dari exchange rate API",
    });
  }

  if (badges.length === 0 && sourceLog.final_source === "model_fallback") {
    badges.push({
      label: "Pengetahuan Model",
      tier: "low",
      description: "Berdasarkan pengetahuan training model AI — perlu verifikasi untuk info terkini",
    });
  }

  return badges;
}

/* ── Response post-processor ──────────────────────────────────────────────── */

/**
 * Apply lightweight post-processing to a model response.
 * Does NOT change meaning — only removes clearly prohibited patterns.
 *
 * Current transformations:
 *   - Strip trailing filler phrases ("Semoga membantu!", "Jangan ragu bertanya!", etc.)
 *
 * @param {string} text - Raw model response
 * @returns {string} Cleaned response text
 */
export function postProcessResponse(text) {
  if (!text || typeof text !== "string") return text;

  let cleaned = text;

  // Remove trailing filler closings
  cleaned = cleaned.replace(
    /\n*(semoga membantu\.?|semoga bisa membantu\.?|jangan ragu (untuk |)bertanya\.?|feel free to ask\.?|hope this helps\.?)\s*[!.]*\s*$/gi,
    ""
  ).trim();

  return cleaned;
}

/* ── Query type classifier (for schema selection) ─────────────────────────── */

/**
 * Select the appropriate response schema based on intent.
 *
 * @param {string} intentPrimary - From detectIntent().primary
 * @returns {object} GENERAL_RESPONSE_SCHEMA or PROCEDURAL_RESPONSE_SCHEMA
 */
export function selectResponseSchema(intentPrimary) {
  const proceduralIntents = new Set(["procedural", "confused_procedural"]);
  return proceduralIntents.has(intentPrimary)
    ? PROCEDURAL_RESPONSE_SCHEMA
    : GENERAL_RESPONSE_SCHEMA;
}
